version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DEVELOPMENT_MODE=true

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ispengestopp_dev
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

