version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ispengestopp_dev
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - DEVELOPMENT_MODE=true
