apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: ispengestopp-alerts
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#syfo-alarm'
      prependText: '<!here> | '
  alerts:
    - alert: ISPENGESTOPP IS DOWN
      expr: sum(up{app="ispengestopp", job="kubernetes-pods"}) == 0
      for: 30s
      description: "Det er ingen pods for app kjørende i namespace og dermed er appen nede"
      action: "Undersøk hvorfor pods er nede og få den kjørende igjen!"
      severity: danger
