apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispengestopp
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  startup:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 128Mi
  ingresses:
    - "https://ispengestopp.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
    outbound:
      external:
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: istilgangskontroll
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: ispengestopp-db
        diskAutoresize: true
  env:
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
