apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispengestopp
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvispengestopp
        mountPath: /secrets/serviceuser
  ingresses:
    - "https://ispengestopp.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://ispengestopp.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  webproxy: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: DATABASE_MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: DATABASE_NAME
      value: ispengestopp
    - name: ISPENGESTOPP_DB_URL
      value: jdbc:postgresql://A01DBVL013.adeo.no:5432/ispengestopp
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.nais.adeo.no"
