apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispengestopp
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  startup:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    - "https://ispengestopp.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
    outbound:
      external:
        - host: "kafka-schema-registry.nais-q.adeo.no"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: ispengestopp-db
        diskAutoresize: true
  envFrom:
    - secret: ispengestopp-serviceuser
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: "https://kafka-schema-registry.nais-q.adeo.no"
    - name: TOGGLE_USE_AIVEN_TOPIC
      value: "true"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
