apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispengestopp
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  startup:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - "https://ispengestopp.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
    outbound:
      external:
        - host: "syfo-tilgangskontroll.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: ispengestopp-db
        diskAutoresize: true
  env:
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
