name: kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/kafka-stoppautomatikk.yaml'
      - '.nais/kafka/stoppautomatikk.yaml'
      - '.nais/kafka/dev.json'
      - '.nais/kafka/prod.json'

permissions:
  id-token: write

jobs:
  deploy-kafka-stoppautomatikk-dev:
    name: Deploy Kafka topic stoppautomatikk to NAIS dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/stoppautomatikk.yaml
          VARS: .nais/kafka/dev.json

  deploy-kafka-stoppautomatikk-prod:
    name: Deploy Kafka topic stoppautomatikk to NAIS prod-gcp
    needs: deploy-kafka-stoppautomatikk-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/stoppautomatikk.yaml
          VARS: .nais/kafka/prod.json
